version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moviesLibrary2
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

  movies-library2:
    build: .
    container_name: Movies-Library2-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/moviesLibrary2
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpassword
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: