version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moviesLibrary2
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  Movies-Library2:
    image: springbootapp:latest
    container_name: Movies-Library2-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/moviesLibrary2
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpassword
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8989:8989"
    depends_on:
      - mysql

volumes:
  mysql-data:
